// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package model

type Item struct {
	ID          string `json:"id"`
	Deleted     bool   `json:"deleted"`
	Type        string `json:"type"`
	By          string `json:"by"`
	Time        int    `json:"time"`
	Text        string `json:"text"`
	Dead        bool   `json:"dead"`
	Parent      int    `json:"parent"`
	Poll        int    `json:"poll"`
	Kids        []int  `json:"kids"`
	URL         string `json:"url"`
	Score       int    `json:"score"`
	Title       string `json:"title"`
	Parts       []int  `json:"parts"`
	Descendants int    `json:"descendants"`
}

type User struct {
	ID       string `json:"id"`
	Created  int    `json:"created"`
	Delay    int    `json:"delay"`
	Karma    int    `json:"karma"`
	Submited []int  `json:"submited"`
}
