// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     int    `json:"id"`
	Text   string `json:"text"`
	Parent int    `json:"parent"`
}

type Item struct {
	ID          int        `json:"id"`
	Deleted     bool       `json:"deleted"`
	Type        string     `json:"type"`
	By          string     `json:"by"`
	Time        int        `json:"time"`
	Text        string     `json:"text"`
	Dead        bool       `json:"dead"`
	Parent      int        `json:"parent"`
	Poll        int        `json:"poll"`
	Kids        []int      `json:"kids"`
	URL         string     `json:"url"`
	Score       int        `json:"score"`
	Title       string     `json:"title"`
	Parts       []int      `json:"parts"`
	Descendants int        `json:"descendants"`
	Comments    []*Comment `json:"comments"`
	Page        int        `json:"page"`
}

type User struct {
	ID       int   `json:"id"`
	Created  int   `json:"created"`
	Delay    int   `json:"delay"`
	Karma    int   `json:"karma"`
	Submited []int `json:"submited"`
}
